kind: ResourceQuota
apiVersion: v1
metadata:
  name: quota
  namespace: argocd-demo
spec:
  hard:
    limits.cpu: '2'
    limits.memory: 2Gi
    pods: '4'
    requests.cpu: '1'
    requests.memory: 1Gi
    persistentvolumeclaims: "4"
    secrets: "10" 
    services: "10"
