apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd-demo
  name: team-lead
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["project", "pods", "deployment", "service", "route"]
  verbs: ["get", "watch", "list"]
