apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd-demo
  name: team-lead
rules:
- verbs: ["get", "watch", "list"]
  apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services"]
- verbs: ["get", "watch", "list"]
  apiGroups: ["apps"]
  resources: ["deployments"]
- verbs: ["get", "watch", "list"]    
  apiGroups: ["", "route.openshift.io"]
  resources: ["routes"]
- verbs: ["get"]    
  apiGroups: ["", "project.openshift.io"]
  resources: ["projects"]
