apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd-demo
  name: dev
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["project", "pods"]
  verbs: ["get", "watch", "list"]
- verbs: ["get"]    
  apiGroups: ["", "project.openshift.io"]
  resources: ["projects"]
